# Generated by Django 5.1.15 on 2026-08-04 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0007_organizationmember_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="workspace_visibility",
            field=models.CharField(
                choices=[
                    ("auto", "Auto"),
                    ("open", "Open"),
                    ("restricted", "Restricted"),
                ],
                default="auto",
                help_text="Controls how workspace visibility restrictions are applied: 'auto' enables restrictions once any workspace assignment exists, 'open' keeps all workspaces visible to all members, 'restricted' only shows assigned workspaces.",
                max_length=16,
                verbose_name="workspace visibility",
            ),
        ),
    ]
